Repository grafana/pyroscope, pull requests merged in 2021-09, with the labels that each got.

#383 Fixes diff view color issue
  jest.config.js
  scripts/webpack/webpack.panel.js
  webapp/__tests__/color.spec.js
  webapp/javascript/components/FlameGraph/FlameGraphComponent/color.js
  webapp/javascript/components/FlameGraph/FlameGraphComponent/index.jsx
  webapp/javascript/components/Footer.jsx
  webapp/javascript/components/ProfilerHeader.jsx
  webapp/javascript/components/ProfilerTable.jsx
  webapp/javascript/components/PyroscopeApp.jsx
  webapp/javascript/components/Sidebar.jsx
  webapp/javascript/components/TagsBar.jsx
  webapp/javascript/util/color.js
Labels: frontend

#373 Server PR benchmark
  .gitignore
  benchmark/Dockerfile
  benchmark/README.md
  benchmark/ci/pr/README.md
  benchmark/ci/pr/dangerfile.js
  benchmark/ci/pr/docker-compose.yml
  benchmark/ci/pr/grafana-provisioning/.gitkeep
  benchmark/ci/pr/report.yaml
  benchmark/ci/pr/run-benchmark.sh
  benchmark/cmd/command/ci-report.go
  benchmark/cmd/command/loadgen.go
  benchmark/cmd/command/log.go
  benchmark/cmd/command/queryprom.go
  benchmark/cmd/command/root.go
  benchmark/cmd/command/screenshot.go
  benchmark/config/config.go
  benchmark/docker-compose.yml
  benchmark/internal/cireport/cireport.go
  benchmark/internal/cireport/cireport_test.go
  benchmark/internal/cireport/imagereport.go
  benchmark/internal/cireport/resources/image-report.gotpl
  benchmark/internal/cireport/resources/pr.gotpl
  benchmark/internal/cireport/screenshotter.go
  benchmark/internal/cireport/tablereport.go
  benchmark/internal/cireport/tablereport_test.go
  benchmark/internal/cireport/testdata/tablereport.golden
  benchmark/internal/cireport/upload.go
  benchmark/internal/config/config.go
  benchmark/internal/config/interface.go
  benchmark/internal/loadgen/loadgen.go
  benchmark/internal/promquery/promquery.go
  benchmark/package.json
  benchmark/prometheus/prometheus.yml
  benchmark/run-parameters.env
  benchmark/start.sh
  benchmark/with-env.sh
  benchmark/yarn.lock
  go.mod
  go.sum
  monitoring/Makefile
  monitoring/benchmark-pr.jsonnet
  monitoring/benchmark.jsonnet
  monitoring/gen/benchmark-dashboard.json
  monitoring/gen/benchmark-pr.json
  monitoring/gen/dashboard.json
  monitoring/lib/dashboard.libsonnet
  monitoring/lib/server-comparison.libsonnet
Labels: benchmarking

#385 Optimize cache persistence
  .gitattributes
  go.mod
  go.sum
  monitoring/gen/benchmark-dashboard.json
  monitoring/gen/dashboard.json
  monitoring/lib/dashboard.libsonnet
  pkg/storage/cache/cache.go
  pkg/storage/cache/cache_test.go
  pkg/storage/cache/lfu/LICENSE.txt
  pkg/storage/cache/lfu/README.md
  pkg/storage/cache/lfu/lfu.go
  pkg/storage/cache/lfu/lfu_test.go
  pkg/storage/codec.go
  pkg/storage/dict/dict.go
  pkg/storage/dict/trie.go
  pkg/storage/metrics.go
  pkg/storage/periodic.go
  pkg/storage/storage.go
  pkg/storage/tree/serialize.go
  pkg/storage/tree/tree.go
Labels: enhancement, storage, 🧹 cleanup, backend, performance

#426 Update readme
  README.md
Labels: documentation

#425 Fix intersection
  pkg/storage/dimension/dimension.go
  pkg/storage/dimension/dimension_test.go
Labels: bug, storage
