Repository grafana/pyroscope, pull requests merged in 2021-05, with the labels that each got.

#194 fix issue#163: nil reference when paring the tries
  pkg/convert/parser.go
  pkg/server/ingest.go
Labels: bug

#200 Add .Net support
  Makefile
  examples/dotnet/3.1/fast-slow/Dockerfile
  examples/dotnet/3.1/fast-slow/docker-compose.yml
  examples/dotnet/3.1/fast-slow/example/Example.csproj
  examples/dotnet/3.1/fast-slow/example/Program.cs
  examples/dotnet/3.1/web/Dockerfile
  examples/dotnet/3.1/web/docker-compose.yml
  examples/dotnet/3.1/web/example/Example.csproj
  examples/dotnet/3.1/web/example/Program.cs
  examples/dotnet/5.0/fast-slow/Dockerfile
  examples/dotnet/5.0/fast-slow/docker-compose.yml
  examples/dotnet/5.0/fast-slow/example/Example.csproj
  examples/dotnet/5.0/fast-slow/example/Program.cs
  examples/dotnet/5.0/web/Dockerfile
  examples/dotnet/5.0/web/docker-compose.yml
  examples/dotnet/5.0/web/example/Example.csproj
  examples/dotnet/5.0/web/example/Program.cs
  go.mod
  go.sum
  pkg/agent/dotnetspy/dotnetspy.go
  pkg/agent/dotnetspy/placeholder.go
  pkg/agent/dotnetspy/session.go
  pkg/agent/session.go
  pkg/agent/spy/spy.go
  pkg/analytics/analytics.go
  webapp/javascript/util/format.js
Labels: dotnet

#203 Fix dotnetspy panic on premature exit and add tests.
  pkg/agent/dotnetspy/dotnetspy.go
  pkg/agent/dotnetspy/dotnetspy_suite_test.go
  pkg/agent/dotnetspy/dotnetspy_test.go
  pkg/agent/dotnetspy/session.go
Labels: dotnet

#202 support the compile on linux system, like ubuntu and centos
  Makefile
Labels: enhancement

#190 Fix issue #154: Add ability to change sampling rate
  pkg/agent/cli/agent.go
  pkg/agent/gospy/gospy.go
  pkg/agent/profiler/profiler.go
  pkg/agent/selfprofile.go
  pkg/agent/session.go
  pkg/agent/spy/spy.go
  pkg/agent/types/types.go
  pkg/agent/upstream/remote/remote.go
  pkg/agent/upstream/upstream.go
  pkg/cli/cli.go
  pkg/config/config.go
  pkg/exec/cli.go
  pkg/server/ingest.go
  pkg/storage/segment/segment.go
  pkg/storage/segment/serialization.go
  pkg/storage/storage.go
  pkg/storage/tree/flamebearer.go
Labels: backend

#199 fix the issues: #191 and #198
  Makefile
  go.sum
  pkg/agent/gospy/gospy.go
  pkg/agent/gospy/gospy_test.go
  pkg/agent/pprof/LICENSE
  pkg/agent/pprof/README.md
  pkg/agent/pprof/elf.go
  pkg/agent/pprof/map.go
  pkg/agent/pprof/pprof.go
  pkg/agent/pprof/proto.go
  pkg/agent/pprof/protobuf.go
  pkg/agent/selfprofile.go
  pkg/agent/session.go
  pkg/cli/cli.go
  pkg/convert/cli.go
Labels: backend, enhancement

#214 fix the issue #188: add the file name and code line
  pkg/cli/cli.go
  pkg/convert/parser.go
  pkg/exec/cli.go
Labels: backend, enhancement

#215 handle error when starting the server
  pkg/agent/cli/agent.go
  pkg/agent/profiler/profiler.go
  pkg/agent/selfprofile.go
  pkg/agent/session.go
  pkg/agent/session_test.go
  pkg/agent/upstream/remote/remote.go
  pkg/agent/upstream/remote/remote_test.go
  pkg/analytics/analytics_test.go
  pkg/cli/cli.go
  pkg/exec/cli.go
  pkg/server/controller.go
  pkg/server/ingest_test.go
Labels: backend, enhancement
