Repository grafana/pyroscope, pull requests merged in 2021-07, with the labels that each got.

#266 improve tooltip rendering
  package.json
  webapp/javascript/components/FlameGraphRenderer.jsx
  webapp/javascript/index.jsx
  webapp/sass/flamebearer.scss
  yarn.lock
Labels: enhancement, frontend

#295 Protect diagnostic endpoints
  pkg/config/config.go
  pkg/server/controller.go
Labels: backend, security

#299 Replaced no longer maintained jwt-go with golang-jwt/jwt
  go.mod
  go.sum
  pkg/server/controller.go
  pkg/server/handler.go
Labels: backend, security

#297 Add dimension lookup by key labels
  pkg/storage/storage.go
Labels: backend

#293 Metrics exporter
  go.mod
  go.sum
  pkg/agent/session.go
  pkg/agent/upstream/direct/direct.go
  pkg/analytics/analytics.go
  pkg/analytics/analytics_test.go
  pkg/cli/cli.go
  pkg/cli/flags.go
  pkg/cli/flags_test.go
  pkg/cli/server.go
  pkg/cli/server_unix.go
  pkg/cli/testdata/server.yml
  pkg/config/config.go
  pkg/exporter/exporter.go
  pkg/exporter/exporter_test.go
  pkg/exporter/labels.go
  pkg/exporter/node.go
  pkg/flameql/error.go
  pkg/flameql/flameql.go
  pkg/flameql/flameql_suite_test.go
  pkg/flameql/flameql_test.go
  pkg/flameql/parse.go
  pkg/flameql/parse_test.go
  pkg/flameql/tag_key.go
  pkg/flameql/tag_key_test.go
  pkg/server/build_test.go
  pkg/server/config_test.go
  pkg/server/controller.go
  pkg/server/ingest.go
  pkg/server/ingest_test.go
  pkg/server/render_test.go
  pkg/storage/ingester.go
  pkg/storage/query_test.go
  pkg/storage/segment/key.go
  pkg/storage/storage_test.go
  pkg/storage/tree/tree.go
  scripts/generate-sample-config/main.go
Labels: backend, enhancement
