Repository grafana/pyroscope, pull requests merged in 2021-12, with the labels that each got.

#577 fix: generate trie from pprof at scraping correctly
  pkg/scrape/pprof.go
Labels: bug

#585 fix: use default config file
  benchmark/internal/config/config.go
  go.mod
  go.sum
  pkg/cli/command.go
  pkg/cli/command_test.go
  pkg/cli/testdata/test-config.yml
  pkg/config/config.go
Labels: bug

#588 fix: trigger retention task when no levels are configured
  pkg/storage/segment/retention.go
  pkg/storage/segment/timeline.go
  pkg/storage/storage.go
Labels: bug, storage

#574 chore(grafana-panel): move grafana panel plugin to this repo
  .eslintignore
  .github/workflows/cypress-tests.yml
  .github/workflows/tests-js-snapshot.yml
  .gitignore
  .storybook/main.js
  Dockerfile
  cypress/integration/panel/basic.ts
  cypress/integration/webapp/api.ts
  cypress/integration/webapp/basic.ts
  cypress/integration/webapp/e2e.ts
  cypress/integration/webapp/lang-smoke.ts
  cypress/integration/webapp/pages.ts
  cypress/integration/webapp/sidebar.ts
  cypress/snapshots/basic.ts/grafana-simple-golang-app-cpu.snap.png
  cypress/snapshots/basic.ts/pyroscope.server.alloc_objects-flamegraph.snap.png
  cypress/snapshots/basic.ts/pyroscope.server.alloc_objects-table.snap.png
  grafana-plugin/panel/LICENSE
  grafana-plugin/panel/README.md
  grafana-plugin/panel/cypress.json
  grafana-plugin/panel/docker-compose.yml
  grafana-plugin/panel/grafana-provisioning/dashboards/dashboard.json
  grafana-plugin/panel/grafana-provisioning/dashboards/main.yml
  grafana-plugin/panel/grafana-provisioning/dashboards/single-panel.json
  grafana-plugin/panel/grafana-provisioning/datasources/datasources.yml
  grafana-plugin/panel/grafana.ini
  grafana-plugin/panel/src/SimplePanel.module.css
  grafana-plugin/panel/src/SimplePanel.tsx
  grafana-plugin/panel/src/module.ts
  grafana-plugin/panel/src/plugin.json
  grafana-plugin/panel/src/styles.css
  grafana-plugin/panel/src/types.ts
  package.json
  scripts/cypress-screenshots.sh
  scripts/jest-snapshots/run-docker.sh
  scripts/run-tests.sh
  scripts/webpack/webpack.grafana.ts
  scripts/webpack/webpack.panel.js
  stories/Flamegraph.stories.tsx
  tsconfig.json
  webapp/cypress.json
  webapp/javascript/components/ComparisonApp.jsx
  webapp/javascript/components/FlameGraph/FlameGraphComponent/Flamegraph.ts
  webapp/javascript/components/FlameGraph/FlameGraphComponent/Tooltip.spec.tsx
  webapp/javascript/components/FlameGraph/FlameGraphComponent/Tooltip.tsx
  webapp/javascript/components/FlameGraph/FlameGraphRenderer.jsx
  webapp/javascript/components/PyroscopeApp.jsx
  webapp/javascript/components/Sidebar.tsx
  webapp/javascript/components/Toolbar.spec.tsx
  webapp/javascript/components/Toolbar.tsx
  webapp/javascript/ui/Button.tsx
  webapp/javascript/ui/Sidebar.tsx
  yarn.lock
Labels: lfs-detected!

#611 fix: assets handling when using base-url argument
  .gitignore
  Dockerfile
  Makefile
  pkg/server/controller.go
  pkg/server/handler.go
  pkg/server/oauth_base.go
  pkg/server/oauth_github.go
  pkg/server/oauth_gitlab.go
  pkg/server/oauth_google.go
  pkg/server/testdata/Caddyfile
  pkg/server/testdata/docker-compose.yml
  scripts/webpack/webpack.common.js
  webapp/javascript/components/Sidebar.module.css
  webapp/javascript/components/Sidebar.tsx
  webapp/javascript/index.jsx
  webapp/javascript/redux/actions.js
  webapp/javascript/util/baseurl.js
  webapp/javascript/util/updateRequests.js
  webapp/sass/profile.scss
  webapp/templates/forbidden.html
  webapp/templates/index.html
  webapp/templates/login.html
  webapp/templates/redirect.html
  webapp/templates/welcome.html
Labels: bug, frontend, backend

#662 feat(pull-mode): adds file discovery mechanism
  go.mod
  pkg/cli/server.go
  pkg/scrape/discovery/file/file.go
Labels: enhancement, backend
