Repository grafana/pyroscope, pull requests merged in 2022-03, with the labels that each got.

#737 fix: incorrect reads when downsampling
  pkg/storage/segment/fuzz_test.go
  pkg/storage/segment/retention.go
  pkg/storage/segment/segment.go
  pkg/storage/segment/segment_test.go
  pkg/storage/segment/testdata/issue_715
Labels: bug

#916 chore: move web-postinstall script to js
  package.json
  scripts/web-postinstall.js
  scripts/web-postinstall.sh
  yarn.lock
Labels: has conflicts

#923 fix: agent authorization
  pkg/api/authz/authz.go
  pkg/server/controller.go
Labels: bug, backend, security

#925 feat: add dedicated profiles storage with support for retention policy
  cmd/pyroscope/command/admin.go
  pkg/admin/admin_integration_test.go
  pkg/admin/cli.go
  pkg/admin/client.go
  pkg/admin/controller.go
  pkg/admin/controller_test.go
  pkg/admin/server.go
  pkg/cli/server.go
  pkg/config/config.go
  pkg/server/controller.go
  pkg/server/render.go
  pkg/server/render_test.go
  pkg/storage/cleanup.go
  pkg/storage/profile.go
  pkg/storage/profile_test.go
  pkg/storage/retention.go
  pkg/storage/segment/key.go
  pkg/storage/storage.go
  pkg/storage/storage_delete_test.go
  pkg/storage/storage_get.go
  pkg/storage/storage_merge.go
  pkg/storage/storage_put.go
Labels: storage, backend

#962 fix: allow cache eviction while purging storage
  pkg/storage/db.go
  pkg/storage/storage.go
Labels: bug, storage
