Repository grafana/pyroscope, pull requests merged in 2022-08, with the labels that each got.

#1410 fix(webapp): refresh data when (re)submitting query
  cypress/integration/webapp/routes.ts
  webapp/javascript/components/QueryInput/QueryInput.module.scss
  webapp/javascript/components/QueryInput/QueryInput.spec.tsx
  webapp/javascript/components/QueryInput/QueryInput.tsx
  webapp/javascript/components/TagsBar.tsx
  webapp/javascript/components/Toolbar.tsx
  webapp/javascript/pages/ContinuousComparisonView.tsx
  webapp/javascript/pages/ContinuousDiffView.tsx
  webapp/sass/components/tagsbar.scss
Labels: frontend

#1314 feat(ebpf): pythonless, portable ebpf
  .dockerignore
  .github/workflows/lint-go.yml
  Dockerfile
  Makefile
  cmd/pyroscope/command/ebpf.go
  cmd/pyroscope/command/ebpf_stub.go
  cmd/pyroscope/command/root.go
  go.mod
  go.sum
  pkg/agent/ebpfspy/bpf/.gitignore
  pkg/agent/ebpfspy/bpf/Makefile
  pkg/agent/ebpfspy/bpf/profile.bpf.c
  pkg/agent/ebpfspy/bpf/profile.bpf.h
  pkg/agent/ebpfspy/cpuonline/cpuonline.go
  pkg/agent/ebpfspy/ebpfspy_linux.go
  pkg/agent/ebpfspy/sd/k8s.go
  pkg/agent/ebpfspy/sd/k8s_test.go
  pkg/agent/ebpfspy/sd/sd.go
  pkg/agent/ebpfspy/session_linux.go
  pkg/agent/ebpfspy/session_maps_linux.go
  pkg/agent/ebpfspy/symbols_linux.go
  pkg/agent/session.go
  pkg/agent/spy/spy.go
  pkg/config/config.go
  pkg/exec/ebpf.go
  pkg/util/genericlru/generic_lru.go
  revive.toml
  scripts/generate-build-flags.sh
  third_party/bcc/.gitignore
  third_party/bcc/Makefile
  third_party/libbpf/.gitignore
  third_party/libbpf/Makefile
Labels: lfs-detected!, has conflicts

#1355 chore(webapp): cleanup features
  webapp/javascript/components/Settings/index.tsx
  webapp/javascript/components/Sidebar.tsx
  webapp/javascript/index.tsx
  webapp/javascript/util/features.ts
  webapp/templates/index.html
Labels: has conflicts
