Repository grafana/pyroscope, pull requests merged in 2022-01, with the labels that each got.

#672 fix: register all pprof handlers
  pkg/server/controller.go
Labels: bug

#684 fix: pyrobench report path
  benchmark/dangerfile.js
Labels: bug, ops

#678 feat: add scrape metrics for pull mode
  pkg/adhoc/pull.go
  pkg/cli/server.go
  pkg/scrape/manager.go
  pkg/scrape/metrics.go
  pkg/scrape/scrape.go
  pkg/scrape/target.go
Labels: enhancement, backend

#663 perf: optimize ingestion
  .gitignore
  benchmark/queries.yml
  pkg/adhoc/pull.go
  pkg/cli/server.go
  pkg/scrape/manager.go
  pkg/scrape/metrics.go
  pkg/scrape/pprof.go
  pkg/scrape/scrape.go
  pkg/scrape/target.go
  pkg/storage/storage.go
  pkg/storage/storage_enqueue.go
  pkg/storage/tree/profile.pb.go
  pkg/storage/tree/profile_vtproto.pb.go
  pkg/storage/tree/tree.go
  pkg/storage/tree/tree_profile.go
  pkg/storage/tree/tree_test.go
Labels: performance

#704 chore(frontend): set a default query when there's nothing in the url
  cypress/integration/webapp/e2e.ts
  webapp/javascript/components/Header.jsx
  webapp/javascript/components/NameSelector.spec.tsx
  webapp/javascript/components/NameSelector.tsx
  webapp/javascript/components/TagsBar.jsx
  webapp/javascript/redux/store.ts
Labels: has conflicts

#731 feat: storage.Get tracing
  pkg/server/controller.go
  pkg/storage/segment/segment.go
  pkg/storage/storage_get.go
Labels: enhancement, storage

#726 feat: add http discovery mechanism
  go.mod
  pkg/cli/server.go
  pkg/scrape/discovery/http/fixtures/http_sd.good.json
  pkg/scrape/discovery/http/http.go
  pkg/scrape/discovery/http/http_test.go
  pkg/scrape/model/time.go
Labels: backend

#738 chore(standalone): don't use go template when hydrating
  pkg/structs/flamebearer/html.go
  scripts/webpack/webpack.standalone.ts
  webapp/templates/standalone.html
Labels: has conflicts

#751 fix: return disk space check
  pkg/adhoc/cli.go
  pkg/analytics/analytics_test.go
  pkg/cli/server.go
  pkg/dbmanager/cli.go
  pkg/health/controller.go
  pkg/server/build_test.go
  pkg/server/config_test.go
  pkg/server/controller_gzip_test.go
  pkg/server/controller_https_test.go
  pkg/server/ingest_test.go
  pkg/server/render_test.go
  pkg/storage/storage.go
  pkg/storage/storage_delete_test.go
  pkg/storage/storage_put.go
  pkg/storage/storage_test.go
  pkg/testing/load/cmd/dataloader/main.go
Labels: bug, backend

#752 feat: add debug storage export endpoint
  pkg/server/controller.go
  pkg/storage/debug.go
Labels: enhancement, storage

#753 fix: log raw segment key value if it can't be parsed
  pkg/storage/retention.go
Labels: bug, storage, 🛠 tech-debt

#766 feat: experimental tracing integration
  examples/golang-push/rideshare-tracing/Dockerfile
  examples/golang-push/rideshare-tracing/Dockerfile.loadgen
  examples/golang-push/rideshare-tracing/README.md
  examples/golang-push/rideshare-tracing/bike/bike.go
  examples/golang-push/rideshare-tracing/car/car.go
  examples/golang-push/rideshare-tracing/config.env
  examples/golang-push/rideshare-tracing/docker-compose.yml
  examples/golang-push/rideshare-tracing/go.mod
  examples/golang-push/rideshare-tracing/go.sum
  examples/golang-push/rideshare-tracing/loadgen.go
  examples/golang-push/rideshare-tracing/main.go
  examples/golang-push/rideshare-tracing/ride/ride.go
  examples/golang-push/rideshare-tracing/rideshare/rideshare.go
  examples/golang-push/rideshare-tracing/scooter/scooter.go
  go.mod
  go.sum
  pkg/storage/segment/key.go
  pkg/storage/storage_get.go
  pkg/storage/storage_put.go
Labels: enhancement, discussion, ux
