Repository grafana/pyroscope, pull requests merged in 2022-11, with the labels that each got.

#1613 feat: add sandwich view for table/flamegraph
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/styles.module.scss
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/viewTypes.ts
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
  packages/pyroscope-flamegraph/src/FlameGraph/FlamegraphRenderer.module.scss
  packages/pyroscope-flamegraph/src/SandwichIcon.tsx
  packages/pyroscope-flamegraph/src/Toolbar.tsx
  packages/pyroscope-flamegraph/src/convert/diffTwoProfiles.ts
  packages/pyroscope-flamegraph/src/convert/flamebearersToTree.ts
  packages/pyroscope-flamegraph/src/convert/sandwichViewProfiles.spec.ts
  packages/pyroscope-flamegraph/src/convert/sandwichViewProfiles.ts
  packages/pyroscope-flamegraph/src/convert/testData.ts
  webapp/javascript/index.tsx
  webapp/javascript/ui/Button.module.scss
  webapp/javascript/ui/Button.tsx
  webapp/sass/variables.css
Labels: frontend

#1647 chore: moved export profile to Toolbar
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Header.module.css
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Header.tsx
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.spec.tsx
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
  packages/pyroscope-flamegraph/src/Toolbar.tsx
  webapp/javascript/components/ExportData.tsx
Labels: frontend

#1658 feat: show gif when heatmap has no selection
  lib/types.d.ts
  webapp/javascript/components/Heatmap/index.tsx
  webapp/javascript/pages/ExemplarsSingleView.module.scss
  webapp/javascript/pages/ExemplarsSingleView.tsx
  webapp/javascript/pages/heatmapSelection.gif
  webapp/javascript/redux/reducers/tracing.ts
  webapp/javascript/ui/StatusMessage/StatusMessage.module.scss
  webapp/javascript/ui/StatusMessage/index.tsx
Labels: frontend

#1650 chore(webapp): Format tag explorer table to proper units
  webapp/javascript/pages/TagExplorerView.tsx
Labels: frontend

#1683 chore(frontend): implements subtract function
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/LogoLink.tsx
  packages/pyroscope-flamegraph/src/convert/flamebearersToTree.ts
  packages/pyroscope-flamegraph/src/convert/sandwichViewProfiles.ts
  packages/pyroscope-flamegraph/src/convert/subtract.ts
  packages/pyroscope-flamegraph/src/convert/testData.ts
  packages/pyroscope-flamegraph/src/index.node.ts
  webapp/javascript/pages/TagExplorerView.tsx
Labels: frontend

#1672 feat: add single, comparison, diff tabs to heatmap page
  webapp/javascript/components/ChartTitle.module.scss
  webapp/javascript/components/ChartTitle.tsx
  webapp/javascript/components/TimelineTitle.tsx
  webapp/javascript/pages/ContinuousComparisonView.tsx
  webapp/javascript/pages/ContinuousDiffView.tsx
  webapp/javascript/pages/ContinuousSingleView.tsx
  webapp/javascript/pages/ExemplarsSingleView.module.scss
  webapp/javascript/pages/ExemplarsSingleView.tsx
  webapp/javascript/pages/HeatmapIcons.tsx
  webapp/javascript/pages/heatmapSelectionPreview.gif
  webapp/javascript/pages/loading.ts
  webapp/javascript/redux/reducers/tracing.ts
  webapp/javascript/services/render.ts
Labels: frontend

#1694 fix: heatmap y-axis value with "<"
  webapp/javascript/components/Heatmap/Heatmap.module.scss
Labels: frontend

#1674 feat(flamegraph): Redesign flamegraph toolbar to allow for more interactions
  cypress/integration/webapp/basic.ts
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
  packages/pyroscope-flamegraph/src/Icons.tsx
  packages/pyroscope-flamegraph/src/SandwichIcon.tsx
  packages/pyroscope-flamegraph/src/SharedQueryInput.module.scss
  packages/pyroscope-flamegraph/src/Toolbar.module.css
  packages/pyroscope-flamegraph/src/Toolbar.module.scss
  packages/pyroscope-flamegraph/src/Toolbar.spec.tsx
  packages/pyroscope-flamegraph/src/Toolbar.tsx
  packages/pyroscope-flamegraph/src/__snapshots__/Toolbar.spec.tsx.snap
  packages/pyroscope-flamegraph/src/index.spec.tsx
  webapp/javascript/components/ExportData.module.scss
  webapp/javascript/components/ExportData.tsx
  webapp/sass/profile.scss
  webapp/sass/variables.css
Labels: frontend, has conflicts

#1703 feat: enable "reset view" button when table item is highlighted
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
Labels: frontend

#1700 chore: Update custom icons for sidebar
  webapp/javascript/components/Sidebar.tsx
  webapp/javascript/components/SidebarCustomIcons.tsx
Labels: frontend

#1698 feat: add Fit Mode to Context Menu
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.spec.tsx
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/styles.module.scss
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
Labels: frontend

#1695 feat(webapp): Make explore page show precise numbers in table
  packages/pyroscope-flamegraph/src/format/format.spec.ts
  packages/pyroscope-flamegraph/src/format/format.ts
  webapp/javascript/pages/TagExplorerView.module.scss
  webapp/javascript/pages/TagExplorerView.tsx
  webapp/javascript/pages/formatTableData.spec.ts
  webapp/javascript/pages/formatTableData.ts
Labels: frontend

#1638 feat(webapp): Add relative time period dropdown to comparison / diff view
  webapp/javascript/components/DateRangePicker.tsx
  webapp/javascript/components/SideTimelineComparator/index.tsx
  webapp/javascript/components/SideTimelineComparator/periods.ts
  webapp/javascript/components/SideTimelineComparator/styles.module.scss
  webapp/javascript/components/TimelineChart/SyncTimelines/SyncTimelines.spec.tsx
  webapp/javascript/components/TimelineChart/SyncTimelines/getSelectionBoundaries.ts
  webapp/javascript/components/TimelineChart/SyncTimelines/index.tsx
  webapp/javascript/components/TimelineChart/SyncTimelines/useSync.ts
  webapp/javascript/pages/ContinuousComparison.module.css
  webapp/javascript/pages/ContinuousComparisonView.tsx
  webapp/javascript/pages/ContinuousDiffView.tsx
  webapp/javascript/redux/reducers/continuous.ts
  webapp/javascript/redux/reducers/continuous/state.ts
  webapp/javascript/ui/Popover.tsx
Labels: frontend

#1720 feat(webapp): Display units in pie chart tooltip
  webapp/javascript/pages/TagExplorerView.tsx
  webapp/javascript/pages/formatTableData.ts
  webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/PieChart/Interactivity.plugin.ts
  webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/PieChart/index.tsx
  webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/PieChartTooltip/index.tsx
  webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/index.tsx
Labels: frontend

#1718 fix(webapp): WHERE selector width when value too long for displaying
  webapp/javascript/pages/TagExplorerView.module.scss
  webapp/javascript/pages/TagExplorerView.tsx
Labels: frontend

#1697 feat: show percentages for diff table instead of absolute values
  cypress/integration/webapp/basic.ts
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
  packages/pyroscope-flamegraph/src/ProfilerTable.tsx
  packages/pyroscope-flamegraph/src/Toolbar.module.scss
  packages/pyroscope-flamegraph/src/Toolbar.spec.tsx
  packages/pyroscope-flamegraph/src/Toolbar.tsx
  packages/pyroscope-flamegraph/src/Tooltip/FlamegraphTooltip.tsx
  packages/pyroscope-flamegraph/src/Tooltip/TableTooltip.spec.tsx
  packages/pyroscope-flamegraph/src/Tooltip/TableTooltip.tsx
  packages/pyroscope-flamegraph/src/format/format.ts
  webapp/sass/common.scss
Labels: frontend

#1736 fix: delete app also deletes metadata
  pkg/admin/client.go
  pkg/admin/client_test.go
  pkg/admin/controller.go
  pkg/admin/controller_test.go
  pkg/admin/server.go
  pkg/api/application.go
  pkg/api/applications.go
  pkg/api/router/router.go
  pkg/cli/app_metadata_migration.go
  pkg/cli/server.go
  pkg/model/appmetadata/application_metadata.go
  pkg/server/apps.go
  pkg/server/controller.go
  pkg/service/application.go
  pkg/service/application_metadata.go
  pkg/service/application_metadata_cache.go
  pkg/service/application_metadata_cache_test.go
  pkg/service/application_metadata_test.go
  pkg/storage/application_service_noop.go
  pkg/storage/storage.go
  pkg/storage/storage_labels.go
  pkg/storage/storage_put.go
  pkg/storage/types.go
Labels: backend

#1731 fix: make reset view available in sandwich mode context menu
  packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
Labels: frontend

#1733 feat: make tag explorer modal adapt to content
  webapp/javascript/pages/tagExplorer/components/TagsSelector.module.scss
  webapp/javascript/pages/tagExplorer/components/TagsSelector.tsx
Labels: frontend

#1734 refactor(webapp): Refactor timeline selection
  webapp/javascript/components/TimelineChart/ContextMenu.plugin.tsx
  webapp/javascript/components/TimelineChart/Selection.plugin.ts
  webapp/javascript/components/TimelineChart/Tooltip.plugin.tsx
  webapp/javascript/components/TimelineChart/types.ts
Labels: frontend

#1742 feat(webapp): add tooltip to main timeline in single view
  webapp/javascript/components/TimelineChart/ExploreTooltip/index.tsx
  webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx
  webapp/javascript/components/TimelineChart/Tooltip.plugin.tsx
  webapp/javascript/components/TimelineTooltip.module.css
  webapp/javascript/components/TimelineTooltip.tsx
  webapp/javascript/pages/ContinuousSingleView.tsx
Labels: frontend

#1737 chore(examples): add new dotnet example
  examples/dotnet/rideshare/.gitignore
  examples/dotnet/rideshare/Dockerfile
  examples/dotnet/rideshare/docker-compose.yml
  examples/dotnet/rideshare/example/.gitignore
  examples/dotnet/rideshare/example/BikeService.cs
  examples/dotnet/rideshare/example/CarService.cs
  examples/dotnet/rideshare/example/Example.csproj
  examples/dotnet/rideshare/example/Folder.DotSettings.user
  examples/dotnet/rideshare/example/OrderService.cs
  examples/dotnet/rideshare/example/Program.cs
  examples/dotnet/rideshare/example/ScooterService.cs
  examples/dotnet/web-new/.gitignore
  examples/dotnet/web-new/Dockerfile
  examples/dotnet/web-new/docker-compose.yml
  examples/dotnet/web-new/example/Example.csproj
  examples/dotnet/web-new/example/Program.cs
Labels: dotnet

#1763 chore(webapp): Moving tabs to MUI
  package.json
  webapp/javascript/pages/adhoc/AdhocComparison.tsx
  webapp/javascript/pages/adhoc/AdhocDiff.tsx
  webapp/javascript/pages/adhoc/AdhocSingle.tsx
  webapp/javascript/pages/exemplars/ExemplarsSingleView.tsx
  webapp/javascript/ui/Tabs.module.scss
  webapp/javascript/ui/Tabs.tsx
  yarn.lock
Labels: frontend

#1749 fix(flamegraph): Make table tooltip invisible when user not hovering on table
  cypress/integration/webapp/basic.ts
  packages/pyroscope-flamegraph/src/Tooltip/Tooltip.module.scss
Labels: frontend

#1754 feat: fix toolbar on narrow screens
  cypress/integration/webapp/basic.ts
  packages/pyroscope-flamegraph/src/SharedQueryInput.module.scss
  packages/pyroscope-flamegraph/src/SharedQueryInput.tsx
  packages/pyroscope-flamegraph/src/Toolbar.module.scss
  packages/pyroscope-flamegraph/src/Toolbar.spec.tsx
  packages/pyroscope-flamegraph/src/Toolbar.tsx
  packages/pyroscope-flamegraph/src/__snapshots__/Toolbar.spec.tsx.snap
  packages/pyroscope-flamegraph/src/index.spec.tsx
Labels: frontend

#1762 chore(webapp): Tag Explorer, select 1st tag automatically
  webapp/javascript/pages/TagExplorerView.tsx
  webapp/javascript/redux/reducers/continuous.ts
  webapp/javascript/redux/reducers/continuous/selectors.ts
  webapp/javascript/redux/reducers/continuous/state.ts
Labels: frontend
