Repository grafana/pyroscope, pull requests merged in 2022-02, with the labels that each got.

#774 chore: add pprof reader benchmark
  pkg/storage/tree/profile_benchmark_test.go
  pkg/storage/tree/testdata/heap.pprof
Labels: backend, performance

#772 improve: fix unsafeStrToSlice panic due to empty string
  pkg/storage/tree/tree_profile.go
Labels: bug, backend

#828 docs: add Jaeger tracing integration example
  examples/tracing/honeycomb/Dockerfile
  examples/tracing/honeycomb/Dockerfile.loadgen
  examples/tracing/honeycomb/README.md
  examples/tracing/honeycomb/bike/bike.go
  examples/tracing/honeycomb/car/car.go
  examples/tracing/honeycomb/config.env
  examples/tracing/honeycomb/docker-compose.yml
  examples/tracing/honeycomb/go.mod
  examples/tracing/honeycomb/go.sum
  examples/tracing/honeycomb/loadgen.go
  examples/tracing/honeycomb/main.go
  examples/tracing/honeycomb/ride/ride.go
  examples/tracing/honeycomb/rideshare/rideshare.go
  examples/tracing/honeycomb/scooter/scooter.go
  examples/tracing/jaeger/Dockerfile
  examples/tracing/jaeger/Dockerfile.loadgen
  examples/tracing/jaeger/README.md
  examples/tracing/jaeger/bike/bike.go
  examples/tracing/jaeger/car/car.go
  examples/tracing/jaeger/config.env
  examples/tracing/jaeger/docker-compose.yml
  examples/tracing/jaeger/go.mod
  examples/tracing/jaeger/go.sum
  examples/tracing/jaeger/grafana/grafana.ini
  examples/tracing/jaeger/grafana/provisioning/datasources/datasources.yml
  examples/tracing/jaeger/loadgen.go
  examples/tracing/jaeger/main.go
  examples/tracing/jaeger/ride/ride.go
  examples/tracing/jaeger/rideshare/rideshare.go
  examples/tracing/jaeger/scooter/scooter.go
Labels: documentation

#826 feat: add an optional name field to the profile data format.
  pkg/adhoc/external_writer.go
  pkg/adhoc/server/convert.go
  pkg/adhoc/server/server.go
  pkg/adhoc/server/server_test.go
  pkg/adhoc/writer.go
  pkg/server/render.go
  pkg/structs/flamebearer/flamebearer.go
  pkg/structs/flamebearer/flamebearer_test.go
Labels: has conflicts

#816 docs: Update deployment diagram for Rust
  .github/markdown-images/deployment.svg
  README.md
  examples/README.md
  translations/README.ch.md
Labels: lfs-detected!

#846 fix: CORS allow credentials
  pkg/config/config.go
  pkg/server/controller.go
Labels: security

#844 feat: adds support for auth to grafana datasource plugin
  grafana-plugin/datasource/grafana-provisioning/datasources/datasources.yml
  grafana-plugin/datasource/src/ConfigEditor.tsx
  grafana-plugin/datasource/src/plugin.json
  grafana-plugin/datasource/src/types.ts
Labels: grafana-datasource

#862 chore: add api error logger
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/api_key.go
  pkg/api/api_key_test.go
  pkg/api/api_suite_test.go
  pkg/api/auth.go
  pkg/api/auth_test.go
  pkg/api/authz/authz.go
  pkg/api/mocks/auth.go
  pkg/api/router/router.go
  pkg/api/user.go
  pkg/api/user_test.go
  pkg/model/api_key.go
  pkg/model/context.go
  pkg/model/user.go
  pkg/server/controller.go
  pkg/server/controller_gzip_test.go
  pkg/server/login.go
  pkg/service/auth.go
  pkg/service/auth_cache.go
  pkg/service/user_test.go
Labels: backend, 🛠 tech-debt

#863 chore: refactor ingest pprof HTTP handler
  pkg/convert/pprof/decoder.go
  pkg/convert/pprof/pprof_suite_test.go
  pkg/convert/pprof/pprof_test.go
  pkg/convert/pprof/reader.go
  pkg/convert/pprof/reader_bench_test.go
  pkg/convert/pprof/testdata/cpu.pb.gz
  pkg/convert/pprof/testdata/heap.pb.gz
  pkg/convert/pprof/writer.go
  pkg/scrape/config/config.go
  pkg/scrape/pprof.go
  pkg/scrape/scrape.go
  pkg/server/ingest.go
  pkg/storage/tree/pprof.go
  pkg/storage/tree/profile_benchmark_test.go
  pkg/storage/tree/profile_extra.go
Labels: backend, 🛠 tech-debt

#898 feat: add pprof profiles multiplexing
  examples/tracing/honeycomb/go.mod
  examples/tracing/honeycomb/go.sum
  examples/tracing/jaeger/go.mod
  examples/tracing/jaeger/go.sum
  pkg/convert/pprof/pprof_test.go
  pkg/convert/pprof/reader.go
  pkg/convert/pprof/testdata/cpu-mux.pb.gz
  pkg/convert/pprof/writer.go
  pkg/storage/tree/profile_extra.go
  scripts/pprof-view/main.go
Labels: backend
