Repository grafana/pyroscope, pull requests merged in 2023-08, with the labels that each got.

#2281 Fix OOM caused by big max_nodes parameter
  pkg/model/flamegraph_diff.go
  pkg/model/flamegraph_diff_test.go
  pkg/model/tree.go
  pkg/model/tree_test.go
Labels: bug, backend

#2289 Add pod disruption budget
  operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
  operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml
  operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml
Labels: packages

#2290 Rename some instances of `Phlare` to `Pyroscope`
  cmd/pyroscope/help-all.txt.tmpl
  cmd/pyroscope/help.txt.tmpl
  pkg/api/memberlist_status.gohtml
  pkg/phlare/phlare.go
Labels: 🛠. refactoring
